#include<iostream.h>
#include<conio.h>
void main()
{
	int a = 7;  //data type integer
	float b = 9.999;  //data type float
	char c = 'H';  // data type character
	cout<<"Print the whole numbers"<<a<<endl; //endl basically means new line if you want your next statement in new line that you have put endl.
	cout<<"Print the real numbers "<<b<<endl;
	cout<<"Print the characters   "<<c<<endl;
	getch();
}
