// Program to perform arithmetic operator using two variable
//Header file
#include<iostream.h>
#include<conio.h>
//Start point of program
void main()
{   //Curly brackets is body
	clrscr(); // clrscr it clears the history of console screen
       int a = 4;  //Declaration of variable and datatype
       int b = 2; //Declaration of variable and datatype
       //Addition
       cout<<"Addition of A and B  "<<a+b<<endl; //endl means the next will be printed in new line
       //Subtraction
       cout<<"Subtraction of A and B  "<<a-b<<endl;
       //Division
       cout<<"Division of A and B  "<<a/b<<endl;
       //Multiplication
       cout<<"Multiplication of A and B  "<<a*b<<endl;
      //Modulus
      cout<<"Remainder of A and B  "<<a%b<<endl;

	getch();
}
