//Program to print number from 10 to 1 (for loop)
//header files
#include<iostream.h>
#include<conio.h>
void main()    // start point of execution
{		//open body of program
	clrscr(); // clears the console screen history
	int x;
	for(x=10;x>=1;x--) //in for loop initializing, condition and increment or decrement  can be done in brackets
	{ //for loop body
	cout<<"Number  "<<x<<endl;
	}

	getch();  //holds console screen
}