//Program to print numbers from 1 to 10
//header files
#include<iostream.h>
#include<conio.h>
void main()     //start point of execution
{                                          //open body of program
	clrscr(); // clear  console screen history
	int a=0;       //initializing variable

	while(a<=10)            //condition
	{   //body of while loop
		cout<<"Number  "<<a<<endl;
		a = a+1; //increment

	}
	getch(); // holds the console screen
}
